msazonov: hw_01: add all task
kaliningleb25/scala_book pull request #8
Opened 2021-05-31 18:39 UTC by eternity0078

2021-06-08 14:45 UTC, a-rudkovskaia commented
It's convenient to use scala worksheets in this chapter, some tasks are implied to be done in scala REPL as it affects the result (e.g. 3d task)

2021-06-09 10:11 UTC, kaliningleb25 requested changes

2021-06-09 10:11 UTC, kaliningleb25 commented on src/main/scala/msazonov/hw_01/Task01.scala
> +        var res: Double = math.sqrt(3)
Please use val where it's applicable

2021-06-09 13:05 UTC, eternity0078 commented on src/main/scala/msazonov/hw_01/Task01.scala
> +        var res: Double = math.sqrt(3)
Done

2021-06-09 13:06 UTC, eternity0078 commented
> It's convenient to use scala worksheets in this chapter, some tasks are implied to be done in scala REPL as it affects the result (e.g. 3d task)

Done

2021-06-16 14:51 UTC, kaliningleb25 approved these changes

2021-07-14 13:26 UTC, a-rudkovskaia approved these changes

2021-08-16 14:42 UTC, kaliningleb25 commented
@eternity0078 please merge

2021-08-23 13:27 UTC, merged